package store

// 句子成分说明 seed 数据（comp_infos 表预置内容）。
//
// 覆盖范围：8 大基础成分、3 类短语状语、12 类常见从句，共 23 个角色；
// 键名与前端成分胶囊文案保持一致（前端匹配不到时回退本地「默认」说明）。
// 文案为通用语法知识整理（2026-09-25），后续可按需增补——追加/修订本切片即可。

// compInfoSeeds 成分说明种子数据。
var compInfoSeeds = []CompInfo{
	// ============ 基础成分 ============
	{Role: "主语",
		What: "句子动作的执行者或被描述的对象，通常由名词、代词或名词短语充当。",
		Why:  "明确「谁」在做这件事，是句子陈述的核心对象；缺失主语的句子通常不完整。",
		How:  "一般置于谓语动词之前；可由名词、人称代词、动名词、不定式或主语从句充当。",
		Demo: "She writes letters every week. —— She 是主语，谓语 writes 与之保持第三人称单数。"},
	{Role: "谓语",
		What: "说明主语「做什么」或「是什么」的动词部分，是句子语法的核心骨架。",
		Why:  "承载时态、语态、语气以及主谓一致等关键语法信息。",
		How:  "须与主语保持人称和数的一致；可由单个实义动词构成，也可由「助动词 + 实义动词」构成复杂谓语。",
		Demo: "She has finished her homework. —— has finished 是谓语，have done 构成现在完成时。"},
	{Role: "宾语",
		What: "动作的承受者，通常紧跟在及物动词或介词之后。",
		Why:  "补全动作的对象信息，回答「对谁 / 对什么」，使句意完整。",
		How:  "由名词、代词宾格、动名词或宾语从句充当；双宾动词后可同时接间接宾语和直接宾语。",
		Demo: "I received a letter yesterday. —— a letter 是直接宾语，received 是其谓语。"},
	{Role: "表语",
		What: "位于系动词（be / become / seem / look / feel 等）之后，说明主语身份、特征或状态的成分，由形容词、名词、介词短语或从句充当。",
		Why:  "与系动词构成「主系表」结构，负责描述主语「是什么 / 怎么样」，与动作型谓语互补。",
		How:  "系动词后接形容词而非副词（She looks beautiful ✓）；表语与主语逻辑呼应，注意数的一致。",
		Demo: "The letter is important. —— important 是表语，说明主语 letter 的性质，系动词 is 连接两者。"},
	{Role: "定语",
		What: "修饰名词或代词、限定其范围与特征的成分；单词作定语通常前置，短语或从句作定语通常后置。",
		Why:  "回答「哪一个 / 什么样的」，让名词所指更精确。",
		How:  "多个形容词前置按「观点→大小→年龄→形状→颜色→国籍→材料」排序；修饰 something / anything 等不定代词时后置（something important）。",
		Demo: "I have something important to tell you. —— important 是后置定语，修饰不定代词 something。"},
	{Role: "状语",
		What: "修饰动词、形容词、副词或整句，说明时间、地点、方式、程度、原因等信息的成分，位置灵活。",
		Why:  "为动作或状态补充「何时 / 何地 / 如何 / 为何」等背景，使表达更具体。",
		How:  "方式副词多置于动词后（He runs fast）；修饰形容词时置于其前（really good）；句首状语后常加逗号。",
		Demo: "She writes letters carefully every week. —— carefully（方式）与 every week（时间）都是状语，依次补充动作细节。"},
	{Role: "补语",
		What: "补充说明宾语身份、状态或动作的成分（宾语补足语），常见于 make / keep / find / consider 等使役、感官动词之后。",
		Why:  "使「宾语 + 补语」形成逻辑上的主谓关系，表达使役、命名、认为等含义，句意才完整。",
		How:  "make him happy / keep the door open；感官动词后接不带 to 的不定式（I saw him leave），变被动语态时须还原 to（He was seen to leave）。",
		Demo: "The news made her happy. —— happy 是宾语补足语，her 与 happy 构成「她很开心」的逻辑主谓关系。"},
	{Role: "同位语",
		What: "紧跟名词或代词之后、对前者作进一步解释说明的成分，多由名词或名词短语充当。",
		Why:  "用同一句话补充前一名词的具体身份或内容，避免另起一句，行文更紧凑。",
		How:  "常用逗号或破折号引出（My friend, Tom, ...）；同位语从句由 that 引导且 that 不可省略（the news that he won）。",
		Demo: "Tom, my best friend, wrote the letter. —— my best friend 是 Tom 的同位语，补充说明其身份。"},

	// ============ 短语状语 ============
	{Role: "时间状语",
		What: "说明动作发生时间的成分，由时间副词或时间介词短语充当。",
		Why:  "回答「什么时候」，并常常决定谓语应选择的时态。",
		How:  "通常置于句尾；为了强调也可置于句首；yesterday / last week 等词前不加介词。",
		Demo: "I received your letter yesterday. —— yesterday 是时间状语，与过去时呼应。"},
	{Role: "地点状语",
		What: "说明动作发生地点的成分，多由介词短语或地点副词充当。",
		Why:  "回答「在哪里」，让句子信息更具体、场景更清晰。",
		How:  "通常置于谓语（或宾语）之后；与时间状语并列时，一般先地点后时间。",
		Demo: "She waited at the bus stop. —— at the bus stop 是地点状语。"},
	{Role: "方式状语",
		What: "说明动作执行方式的成分，多由方式副词或「介词 + 名词」短语充当。",
		Why:  "回答「怎么做」，刻画动作的具体样态。",
		How:  "方式副词多置于动词之后（He writes carefully）；强调时可置于句首；与时间、地点状语并列时通常「方式在前」。",
		Demo: "She reads the letter slowly. —— slowly 是方式状语，说明读信的状态。"},

	// ============ 从句（按功能） ============
	{Role: "主语从句",
		What: "充当主语的从句，由 that / whether 或 wh- 词引导。",
		Why:  "把一个完整事件作为陈述对象，多用于正式书面语。",
		How:  "从句作主语时谓语按单数处理（What he said is true）；为避免头重脚轻，常用 it 作形式主语后置（It is clear that...）。",
		Demo: "It is clear that she received the letter. —— that 从句是真正的主语，it 作形式主语前置。"},
	{Role: "宾语从句",
		What: "充当宾语的从句，由 that（陈述内容）、if / whether（是否）或 wh- 词引导。",
		Why:  "把他人话语、观点或疑问整体纳入句子作宾语，实现间接引语。",
		How:  "从句必须用陈述语序（I don't know where he lives ✓，不说 where does he live）；主句为过去时态时从句时态相应后移（客观真理除外）。",
		Demo: "She said that she had received the letter. —— that 从句作 said 的宾语，时态由完成时后移为过去完成时。"},
	{Role: "表语从句",
		What: "位于系动词之后、充当表语的从句，由 that / whether / because 或 wh- 词引导。",
		Why:  "对主语的内容作出解释和说明，常见于 The fact / The problem / The reason is that... 句式。",
		How:  "引导词 that 一般不省略；正式文体中 The reason is that... 不改用 because；从句保持陈述语序。",
		Demo: "The problem is that we missed the deadline. —— that 从句作表语，说明 problem 的具体内容。"},
	{Role: "同位语从句",
		What: "跟在 news / fact / idea / hope 等抽象名词后、解释其具体内容的从句，由 that 引导。",
		Why:  "把抽象名词的内容展开说清；与定语从句的「修饰」不同，它的作用是「说明内容」。",
		How:  "that 在从句中不充当成分但不可省略；与定语从句的区分：定语从句的 that / which 须在从句中作主语或宾语。",
		Demo: "The news that he won the prize excited us. —— that 从句说明 news 的内容，是同位语从句而非定语从句。"},
	{Role: "定语从句",
		What: "由关系代词（who / whom / whose / which / that）或关系副词（when / where / why）引导、修饰名词的从句，紧随先行词之后。",
		Why:  "把两个短句合并为一句，使名词的限定信息更紧凑、行文更地道。",
		How:  "关系词须在从句中充当成分；指人用 who / that，指物用 which / that；非限制性（有逗号）从句不用 that；介词可提前（the house in which...）。",
		Demo: "The letter that she received yesterday was from Tom. —— that 从句修饰 letter，that 在从句中作 received 的宾语。"},
	{Role: "状语从句",
		What: "由从属连词（when / because / if / although 等）引导、整句充当状语的从句，可置于主句前或后。",
		Why:  "表达时间、原因、条件、让步、目的、结果等逻辑关系，是组织长句的主要手段。",
		How:  "时间、条件从句用一般现在时表将来（主将从现）；从句在句首时后面加逗号；though / although 不能与 but 连用。",
		Demo: "When she received the letter, she smiled. —— when 从句前置提供时间背景，主句陈述结果。"},

	// ============ 从句（状语从句细分） ============
	{Role: "让步状语从句",
		What: "由 although / though / even though 等从属连词引导，表示「尽管……仍然……」的状语从句。",
		Why:  "为句子提供反背景条件，衬托主句事实的成立，增强表达的逻辑层次。",
		How:  "可置于句首（后加逗号）或主句之后；英语中让步从句与主句不能并用 but。",
		Demo: "Although it rained heavily, we went out. —— 从句前置提供让步背景，主句不再加 but。"},
	{Role: "条件状语从句",
		What: "表示条件的状语从句，由 if / unless / as long as 引导，分真实条件句与虚拟条件句。",
		Why:  "说明主句成立的前提，区分「很可能发生」与「假设虚拟」两种情形。",
		How:  "真实条件主将从现（If it rains, we will stay）；虚拟条件用过去式 / 过去完成式，be 统用 were；unless 相当于 if...not。",
		Demo: "If I were you, I would reply at once. —— 与现在事实相反的虚拟条件，be 动词统一用 were。"},
	{Role: "原因状语从句",
		What: "由 because / since / as 引导、说明主句原因的从句。",
		Why:  "交代动作或结论的缘由，使论证有据。",
		How:  "because 语气最强、可直接回答 why；since / as 多表示双方已知的次要原因；原因从句不能与 so 连用。",
		Demo: "She smiled because the letter was from her best friend. —— because 从句给出 smiled 的直接原因。"},
	{Role: "目的状语从句",
		What: "由 so that / in order that 引导、说明主句行为目的的从句。",
		Why:  "点明「为了什么」而做某事，常与情态动词连用。",
		How:  "从句常用 may / might / can / could 等情态动词；短语替代形式为 in order to / so as to（so as to 不放句首）。",
		Demo: "She wrote back so that he could feel her care. —— so that 从句说明写信的目的，从句用 could 呼应。"},
	{Role: "结果状语从句",
		What: "由 so...that / such...that 引导、说明主句行为结果的从句。",
		Why:  "强调程度之深以至于产生某种结果。",
		How:  "so 后接形容词 / 副词（so fast that...），such 后接名词短语（such a good letter that...）；注意 so many / much / few / little + 名词的例外搭配。",
		Demo: "She was so happy that she read the letter twice. —— so + 形容词 happy，that 从句呈现结果。"},
	{Role: "时间状语从句",
		What: "由 when / while / as / before / after / since / until 等引导、说明主句时间关系的从句。",
		Why:  "给主句动作定位时间（同时、先后、延续），使叙事清晰。",
		How:  "时间从句用一般现在时表将来（When he arrives...）；since 从句用过去时、主句用完成时；not...until 意为「直到...才」。",
		Demo: "I have known her since we studied together. —— since 从句用过去时，主句用现在完成时，呼应「从过去延续至今」。"},
}
